### ISSUE TITLE
Basic Features

### ISSUE THREAD

**Issue by ismailsunni** [qgis/QGIS-Hub-Plugin#8]
### Feature description

- [ ] A better way to handle download (e.g. background process)
- [x] Use the thumbnail of the resource in the browser
- [x] #25
- [ ] Load the resource asynchronously
- [x] #26
- [x] Option to choose download folder #18 
- [x] Filtering by resource type #13 
- [x] Full-text search #14 

### Additional context

Currently, the plugin is working (i.e. able to browse, preview, and download)

![image](https://user-images.githubusercontent.com/1421861/233785484-70db3937-df56-4822-9c31-e71c6496f010.png)

**Comment by ismailsunni** [comment]
The missing item is handled in #44
